### ISSUE TITLE
[feature request] extinguishing options / tools

### ISSUE THREAD

**Issue by MRSimpson21** [Seb105/Arma-Wildfire#2]
It would be really nice to have the option to extinguish the fire with an item like a smoke grenade or a fire extinguisher for example.
Or with vehicles like in the old [SCMod](https://steamcommunity.com/sharedfiles/filedetails/?id=1115246886&searchtext=scmod) Addon.

Thanks in advance

**Comment by Seb105** [comment]
I need to rework things a little to do this but yes

**Comment by Seb105** [comment]
I have exposed a function for extinguishing objects: `_tree remoteExecCall ["wildfire_main_fnc_extinguishObject", 2]`

This means firefighting equipment can now be scripted. I won't be adding any as I don't have the art abilities to add that sort of thing to the game.

**Comment by MRSimpson21** [comment]
Ok thank you very much.

I am going to test a little bit and see what comes out.
