### ISSUE TITLE
[feature request] replace burned trees instead of deleting

### ISSUE THREAD

**Issue by Quailsnap** [Seb105/Arma-Wildfire#3]
The SOG: Prairie Fire CDLC has burned/naped/broken trees that could serve as replacements to tree props that have fully 'burned.' Some similar props exist from vanilla/apex. Could these be used instead of deleting the foliage entirely?

**Comment by Seb105** [comment]
I know cup has burned trees, I was thinking of using them.

What vanilla (model or .p3d path) is available? I looked but didn't find any.

**Comment by Seb105** [comment]
in v2.1
